import type {
  ApplicationProcess,
  ApplicationResearchTier,
  SalaryOutlook,
} from "./types";

type VacancySeed = readonly [
  rank: number,
  jobTitle: string,
  company: string,
  location: string,
  deadline: string | null,
  publishedTerms: string,
  compensation: string,
  salaryOutlook: SalaryOutlook,
  fitRating: string,
  researchSummary: string,
];

const VERIFIED_AT = "2026-07-29";
const SHORTLIST = new Set([1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 14, 18, 19, 23]);

const VACANCY_SEEDS = [
  [
    1,
    "Sachbearbeitung Kommunales Krisenmanagement / Business Continuity",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-10",
    "Unbefristet · Voll- oder Teilzeit · Homeoffice",
    "EG 10 TVöD / A 11",
    "yes",
    "A",
    "BWL und Business Administration werden ausdrücklich akzeptiert. Prozesse, Risiken, Projektsteuerung, Beratung und Krisenorganisation passen sehr gut.",
  ],
  [
    2,
    "Digitaler Lotse / Prozessmanager / Datenschutz-Sachbearbeiter",
    "Stadt Krefeld",
    "Krefeld",
    "2026-08-09",
    "Unbefristet · geplanter Beginn 18.02.2027",
    "EG 11 / A 12",
    "yes",
    "A−",
    "Roadmaps, Prozessoptimierung, Softwareeinführungen und Datenschutz. Die App-Projekte sollten als mehrjährige Digitalisierungserfahrung dokumentiert werden.",
  ],
  [
    3,
    "Prozesskoordination im Programmbereich Geschäftsarchitektur",
    "Bundesverwaltungsamt",
    "Düsseldorf oder Köln",
    "2026-08-03",
    "Unbefristet · Voll- oder Teilzeit",
    "EG 11 TVöD Bund",
    "yes",
    "A−/B+",
    "Prozessmanagementsystem, Optimierungen, Qualität, Wirtschaftlichkeit und Anbietersteuerung. Sehr dringliche Bewerbung.",
  ],
  [
    4,
    "Projektmanager Verwaltungsmodernisierung, Digitalisierung und Change",
    "Stadt Ratingen",
    "Ratingen",
    "2026-08-17",
    "Zwei Stellen · unbefristet · Voll- oder Teilzeit",
    "EG 11 / A 12",
    "yes",
    "B+",
    "DMS, E-Akte, Finanzsoftware, Prozessanalysen, Workshops und Change. Kritisch ist der Nachweis dreijähriger entsprechend hochwertiger Projektarbeit.",
  ],
  [
    5,
    "Projektleitung Programmbereich Projektsteuerung",
    "Bundesverwaltungsamt",
    "Düsseldorf oder Köln",
    "2026-08-17",
    "Unbefristet · Voll- oder Teilzeit",
    "EG 11 / A 12–A 13 mZ",
    "yes",
    "B+",
    "Projektpläne, Kosten, Qualität, Ziele, Risiken und Workshops. Vermittlungs- und App-Projekte als verantwortete Projekte mit Ergebnissen darstellen.",
  ],
  [
    6,
    "Experte Contact Center AI, Conversational AI und Agentic AI",
    "KV Nordrhein",
    "Köln",
    "2026-08-27",
    "Arbeitsumfang nicht näher veröffentlicht",
    "EG 13 TV-L",
    "yes",
    "A−/B+",
    "Voice- und Chatbots, Agentic AI, Prompts, Trainingsdaten, APIs, Cloud, Anbieter und Workshops. Eine der stärksten Verbindungen zur OpenAI-API-Praxis.",
  ],
  [
    7,
    "Business Project Manager Conversational AI und Cloud-Technologien",
    "Commerz Direktservice",
    "Duisburg",
    null,
    "Vollzeit · veröffentlicht am 20.07.2026 · keine Frist genannt",
    "Privatwirtschaftlich",
    "open",
    "A−/B+",
    "AI-Chatbots, Voicebots, Agent Assist, Business Cases, KPIs, Roll-outs, Anbieter und Stakeholder. Fehlende Bank- und Contact-Center-Erfahrung ist erklärbar.",
  ],
  [
    8,
    "Strategischer Inhouse Consultant / Projektmanager",
    "KV Nordrhein",
    "Düsseldorf",
    "2026-08-14",
    "Arbeitsumfang nicht näher veröffentlicht",
    "EG 13 TV-L",
    "yes",
    "B+",
    "Strategie, Digitalisierung, E-Health, Reorganisation und Prozessoptimierung. Verlangt werden allerdings etwa fünf Jahre PM- oder Consulting-Erfahrung.",
  ],
  [
    9,
    "Projektmanager IT und Digitalisierung",
    "GELSENDIENSTE",
    "Gelsenkirchen",
    "2026-08-04",
    "Unbefristet · Vollzeit · Teilzeit möglich",
    "EG 10 TVöD",
    "yes",
    "A−/B+",
    "BWL wird akzeptiert. Digitalstrategie, Projektcontrolling, Reporting, Datenschutz, M365 und SAP. Die kurze Frist macht die Stelle besonders dringlich.",
  ],
  [
    10,
    "Digitalisierungsberatung – Schwerpunkt Dokumentenmanagementsysteme",
    "ITK Rheinland",
    "Neuss",
    "2026-08-23",
    "Unbefristet · Vollzeit",
    "Bis EG 10",
    "yes",
    "A−/B+",
    "BWL-nahe Studiengänge werden akzeptiert; DMS-Erfahrung ist erwünscht, aber nicht zwingend. Ist-/Soll-Konzepte, d.velop, Koordination und Schulungen.",
  ],
  [
    11,
    "Übergreifendes Projekt-, Programm- und Prozessmanagement in der IT",
    "Bundesverwaltungsamt",
    "Köln",
    "2026-08-06",
    "Unbefristet · Voll- oder Teilzeit",
    "EG 10 / 11",
    "yes",
    "B+",
    "IT-Governance, Budget, Steuerung, Berichte, Strategie, Innovation und Provider. Benötigt werden zwei Jahre organisationsübergreifende IT-Steuerung oder drei Jahre vergleichbare Erfahrung.",
  ],
  [
    12,
    "Junior Governance Manager",
    "Bank11",
    "Neuss",
    null,
    "Aktuell offen · Vollzeit",
    "Privatwirtschaftlich",
    "open",
    "A−/B+",
    "Richtlinien, Prozesse, MaRisk, DORA, DSGVO, Risiken, Kontrollen, Prüfungen, Berichte und Trainings. Für die Junior-Ausrichtung ungewöhnlich gute BWL- und Prozess-Passung.",
  ],
  [
    13,
    "Digitalization Manager",
    "TARGOBANK",
    "Düsseldorf",
    null,
    "Aktuell offen · unbefristet · Voll- oder Teilzeit · bis 50 % mobil",
    "Privatwirtschaftlich · 13 Gehälter",
    "open",
    "B+",
    "Digitale Initiativen, Automatisierung, Prozessoptimierung und Managementunterlagen. Hürde: zwei bis drei Jahre PM- oder Product-Erfahrung im Finanzumfeld.",
  ],
  [
    14,
    "Prozess- und IT-Koordinator",
    "IDN Infrastruktur-Dienstleistung Niederrhein",
    "Krefeld",
    null,
    "Aktuell offen · unbefristet · mobiles Arbeiten",
    "Privatwirtschaftlich",
    "open",
    "A−/B+",
    "IT-Systeme, Prozesse, Roll-outs, externe Partner, Datenschutz, Dokumentation und Schulungen. ERP, M365, Power Platform oder BI wären Ergänzungsthemen.",
  ],
  [
    15,
    "Teamlead IT Service & Innovation",
    "HITS.nrw",
    "Düsseldorf",
    null,
    "Aktuell offen · unbefristet · Vollzeit · hybrid",
    "Vergütung nicht veröffentlicht",
    "open",
    "B+",
    "Bedarfsanalyse, IT-Services, Helpdesk, Innovation, Schulungen und kleine Teamleitung. ITIL- und Service-Management-Wissen sollte kurzfristig aufgebaut werden.",
  ],
  [
    16,
    "Referent der Geschäftsführung – Strategie, Gremien und Kommunikation",
    "HITS.nrw",
    "Düsseldorf",
    null,
    "Aktuell offen · unbefristet · Vollzeit · hybrid",
    "Vergütung nicht veröffentlicht",
    "open",
    "B+",
    "Transformationsprojekte, Entscheidungsvorlagen, Behörden, Gremien, Workshops und Veranstaltungen. Sehr gute Verbindung zur Kommunikations- und BWL-Erfahrung.",
  ],
  [
    17,
    "IT-Projektmanager / Integration Specialist für Lernplattformen und Campus-Systeme",
    "HITS.nrw",
    "Düsseldorf",
    null,
    "Aktuell offen · zunächst befristet mit Perspektive · hybrid",
    "Vergütung nicht veröffentlicht",
    "open",
    "B",
    "Anforderungen, Tests, Roll-outs, APIs und Datenflüsse. Moodle/ILIAS, HISinOne sowie XML-/REST-Erfahrung fehlen teilweise, sind aber anschlussfähig.",
  ],
  [
    18,
    "Projektmanager Fördermittelmanagement",
    "Connected Mobility Düsseldorf",
    "Düsseldorf",
    null,
    "Ausschreibungsseite aktiv · keine Frist genannt",
    "Vergütung nicht veröffentlicht",
    "open",
    "A−/B+",
    "Förderanträge, Partner, Mittelverwendung, Projektcontrolling und Digitalisierung/Mobilität. Fördermittelrecht ist die zentrale Lernlücke; Status wegen eines vergangenen Startdatums zuerst bestätigen.",
  ],
  [
    19,
    "Project Office Manager – Schwerpunkt Portfoliomanagement",
    "rku.it",
    "Herne",
    null,
    "Aktuell offen · unbefristet · bis 60 % mobil",
    "Versorgungswirtschaftlicher Tarif",
    "open",
    "A−/B+",
    "Portfoliotransparenz, Berichte, Risiken, Prioritäten und Governance. Verlangt werden zwei bis drei Jahre Projekterfahrung.",
  ],
  [
    20,
    "Business Project Manager Dialogplattform",
    "Commerz Direktservice",
    "Duisburg",
    null,
    "Vollzeit · veröffentlicht am 10.07.2026",
    "Privatwirtschaftlich",
    "open",
    "A−/B+",
    "Cloud-Contact-Center, Omnichannel, agile Umsetzung, Regulierung und Übersetzung zwischen Technik, Business und Management.",
  ],
  [
    21,
    "Projektmanager Studiengangsentwicklung",
    "FOM Hochschule",
    "Essen",
    null,
    "Aktuell offen · Vollzeit · 36-Stunden-/Vier-Tage-Woche",
    "Vergütung nicht veröffentlicht",
    "open",
    "A−/B+",
    "Projektsteuerung von der Idee bis zur Umsetzung, digitale Werkzeuge, Marktanforderungen, Akkreditierung und interne Teams.",
  ],
  [
    22,
    "HR-Projektmanager Digitalisierung",
    "Siempelkamp",
    "Krefeld",
    null,
    "Aktuell gelistet",
    "Privatwirtschaftlich",
    "open",
    "A−/B+",
    "Strategische HR- und Digitalprojekte, HR-Systeme, Stammdaten und datenbasierte Personalarbeit. Gute Verbindung aus Recruiting und Data Science; spezifische HRIS-Erfahrung wäre hilfreich.",
  ],
  [
    23,
    "Sachgebietsleitung/Koordination Zweiter Arbeitsmarkt",
    "Stadt Krefeld",
    "Krefeld",
    "2026-08-09",
    "Unbefristet · vorgesehener Beginn 01.06.2027",
    "EG 11 / A 12",
    "yes",
    "B+",
    "Beschäftigungsprojekte, Teamsteuerung, Drittmittel, Budget und Controlling. SGB II/III sowie kommunales Förderrecht sind die Hauptlücken.",
  ],
  [
    24,
    "Projektleitung öffentlich geförderter Maßnahmen",
    "EuBiA",
    "Düsseldorf / Rheinland / Ruhrgebiet",
    null,
    "Aktuell offen · unbefristet · Vollzeit",
    "Vergütung nicht veröffentlicht",
    "open",
    "B+",
    "Mehrere Projekte, Personal, Coaching, Jobcenter, Qualität und Reporting. Sehr passende Recruiting- und Mehrparteienerfahrung; SGB-Kenntnisse fehlen.",
  ],
  [
    25,
    "Inhouse Consultant Strategie und Transformation",
    "Wirtschaftsbetriebe Duisburg",
    "Duisburg",
    null,
    "Aktuell offen · zunächst zwölf Monate · bis 80 % Homeoffice",
    "Im Treffer nicht eindeutig ausgewiesen",
    "open",
    "A−/B+",
    "Strategie 2030, Transformation, KPIs, Workshops und bereichsübergreifende Projekte. Sehr gute Transferrolle.",
  ],
  [
    26,
    "Referent Multiprojektmanagement",
    "Ruhrbahn",
    "Essen",
    null,
    "Aktuell offen · Vollzeit",
    "TV-N NRW",
    "open",
    "B+",
    "Portfolio-Reporting, KPIs, Ressourcen, Kosten, Risiken und PM-Standards. Benötigt werden belastbare Beispiele paralleler Projekte und Managementberichte.",
  ],
  [
    27,
    "Projektmanager Veranstaltungen",
    "Duisburg Kontor",
    "Duisburg",
    null,
    "Aktuell auf der Arbeitgeberseite · Vollzeit",
    "Mindestens analog EG 9a · Jahressonderzahlung",
    "borderline",
    "A−/B",
    "Veranstaltungen, Dienstleister, Budgets, Partner und kreative Konzepte. Erfahrene Quereinsteiger werden berücksichtigt; formelle Veranstaltungserfahrung sollte belegt werden.",
  ],
  [
    28,
    "Projektmanager digitale Ansprache-Services",
    "S-Communication Services",
    "Düsseldorf",
    null,
    "Aktuell offen · Voll- oder Teilzeit · Homeoffice",
    "Vergütung nicht veröffentlicht",
    "open",
    "B+",
    "Digitale Kommunikationsservices für Sparkassen, Projektsteuerung und Stakeholderarbeit. Die Finanzbranche ist die wichtigste fachliche Lücke.",
  ],
  [
    29,
    "Projektleiter Bankorganisation und IT-Projekte",
    "Bank11",
    "Neuss",
    null,
    "Im offiziellen Bank11-Stellenportal weiterhin gelistet · Vollzeit",
    "Privatwirtschaftlich",
    "open",
    "B+",
    "Schnittstelle zwischen Fachbereichen, IT und Regulierung. Die aktuelle Listung wurde zusätzlich im Arbeitgeberportal geprüft.",
  ],
  [
    30,
    "Sachbearbeiter Grundsicherung und Hilfe zum Lebensunterhalt",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-11",
    "Unbefristet · Teilzeit/Homeoffice möglich",
    "EG 9c / A 10",
    "yes",
    "A−",
    "BWL wird akzeptiert. Beratung, Prüfung, Entscheidungen, Hausbesuche und Widersprüche. Sehr KI-resilient; SGB XII muss erlernt werden.",
  ],
  [
    31,
    "Projektassistenz CoLab Curriculumentwicklung",
    "Heinrich-Heine-Universität",
    "Düsseldorf",
    "2026-08-14",
    "Befristet bis 31.12.2029 · Vollzeit",
    "EG 9a TV-L",
    "borderline",
    "A",
    "Projektplanung, Workshops, Prozessdokumentation, Budget, Stakeholder und digitale Kommunikation. Inhaltlich eine der unmittelbarsten Passungen.",
  ],
  [
    32,
    "Projektassistenz Task Force Großprojektmanagement",
    "Bundesverwaltungsamt",
    "Köln",
    "2026-08-12",
    "Auf zwei Jahre befristet",
    "EG 10 TVöD Bund",
    "yes",
    "A−/B+",
    "Portfoliokoordination, Budget- und Projektcontrolling, Workshops, Briefings und Steuerungsunterlagen.",
  ],
  [
    33,
    "Standort-/Projektkoordination",
    "EuBiA",
    "Düsseldorf, Mettmann und Ratingen",
    null,
    "Aktuell im Stellenportal",
    "Nicht veröffentlicht",
    "open",
    "A−/B+",
    "Organisation, Mitarbeitende, Teilnehmende, Auftraggeber und Qualität. Details und konkreter Standort müssen im Portal ausgewählt werden.",
  ],
  [
    34,
    "Jobcoach",
    "EuBiA",
    "Düsseldorf / Rheinland",
    null,
    "Aktuell offen · Voll- oder Teilzeit · unbefristet",
    "Nicht veröffentlicht",
    "open",
    "B+",
    "Einzel- und Gruppencoaching, Bewerbung, Aktivierung und persönliche Stabilisierung. Pädagogische beziehungsweise Coaching-Qualifikation muss argumentiert werden.",
  ],
  [
    35,
    "Portalmanager",
    "Verbraucherzentrale NRW",
    "Düsseldorf",
    "2026-08-09",
    "Unbefristet · Vollzeit",
    "EG 11 TV-L",
    "yes",
    "B−",
    "Webplattform mit mehr als 25 Sites, Releases, Incidents, Dienstleister, Budgets und Schulungen. Starke Drupal-, Web-Infrastruktur- und DNS-Erfahrung wird erwartet.",
  ],
  [
    36,
    "Berater für DMS-Projekte und E-Akte",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-09",
    "Unbefristet · mindestens 35 Stunden · Homeoffice",
    "EG 10 / A 10",
    "yes",
    "B−/C",
    "Aufgaben passen, aber gefordert werden eine formale IT-Qualifikation beziehungsweise Zertifizierungen und SQL-Datenbankmodule.",
  ],
  [
    37,
    "Mitarbeiter Digitalisierung und Prozessmanagement",
    "Stadtwerke Ratingen",
    "Ratingen",
    null,
    "Aktuell offen · mobiles Arbeiten möglich",
    "Nicht veröffentlicht",
    "open",
    "B",
    "Digitale Workflows, Wilken-Software, Anwenderbegleitung, Vertragsadministration, SQL und Excel. Energiewirtschaft und Wilken fehlen.",
  ],
  [
    38,
    "Mitarbeiter TUIV-Support und Digitalisierung",
    "Stadt Kaarst",
    "Kaarst",
    "2026-08-09",
    "Unbefristet · Vollzeit",
    "EG 9a",
    "borderline",
    "B−/C",
    "Anwender-, Arbeitsplatz- und Fachverfahrenssupport. Formale IT- oder Verwaltungsqualifikation ist die Hürde.",
  ],
  [
    39,
    "Sachbearbeitung IT, Digitalisierungsprozesse und Komponenten",
    "Stadt Krefeld",
    "Krefeld",
    "2026-08-02",
    "Unbefristet",
    "EG 9a / A 9",
    "borderline",
    "B−/C",
    "Roll-outs, Administration, Projekte und Support. Formal stärker auf ausgebildete IT- oder Verwaltungsfachkräfte zugeschnitten.",
  ],
  [
    40,
    "ERP-Prozess- und IT-Koordinator Wohnungswirtschaft",
    "Wohnstätte Krefeld",
    "Krefeld",
    null,
    "Aktuell offen · 37 Stunden · mobiles Arbeiten",
    "Tarif Wohnungswirtschaft",
    "open",
    "B−/C",
    "ERP-Strategie, Prozesse, Projekte und Support. Gefordert wird typischerweise eine IT- oder Immobilienausbildung sowie Wohnungswirtschafts-ERP-Erfahrung.",
  ],
  [
    41,
    "IT Service Manager",
    "NRW.BANK",
    "Düsseldorf",
    null,
    "Aktuell offen",
    "Banktarif / individuell",
    "open",
    "B−",
    "BWL wird akzeptiert; Provider, Verträge, SLAs und Cloud passen. Enterprise-IT, Azure/M365, ITIL und Bankregulatorik sind deutliche Lücken.",
  ],
  [
    42,
    "Notfallbeauftragter / Business Continuity Manager",
    "Bank11",
    "Neuss",
    null,
    "Aktuell offen · unbefristet · Vollzeit",
    "Privatwirtschaftlich",
    "open",
    "B−/C",
    "BIA, Notfallpläne, Übungen, IT und Operational Risk. Gefordert werden mehrjährige BCM-Erfahrung und BSI-/ISO-Kenntnisse.",
  ],
  [
    43,
    "Product Owner Eigeneinrichtungen",
    "KV Nordrhein",
    "Düsseldorf",
    "2026-08-02",
    "Arbeitsumfang nicht näher veröffentlicht",
    "EG 14 TV-L",
    "yes",
    "B",
    "Produktvision, Prozesse, Anbieter, Beschaffung, KPIs, Verträge und Recruiting. Sehr hohe Vergütung, aber umfangreiche Kenntnisse des Gesundheitswesens werden erwartet.",
  ],
  [
    44,
    "Koordinator Kompetenz im KI:Expertisezentrum.nrw",
    "Ruhr-Universität Bochum",
    "Bochum",
    "2026-08-09",
    "75–100 % · befristet bis Ende 2030",
    "EG 13 TV-L",
    "yes",
    "B−/C",
    "KI-Weiterbildung, Beratung, Hochschulnetzwerke und Trainings passen ausgezeichnet; ein Masterabschluss wird jedoch verlangt.",
  ],
  [
    45,
    "Sachbearbeitung Ausbildung und Personalentwicklung",
    "Heinrich-Heine-Universität",
    "Düsseldorf",
    "2026-08-24",
    "Befristet",
    "EG 9b TV-L",
    "borderline",
    "A−",
    "Ausbildung, Koordination und Personalentwicklung passen sehr gut. Das 50k-Ziel hängt von der anerkannten Erfahrungsstufe ab.",
  ],
  [
    46,
    "Personalreferent",
    "Kunstsammlung Nordrhein-Westfalen",
    "Düsseldorf",
    "2026-08-31",
    "50 % · befristet bis 31.12.2027",
    "EG 10 TV-L bei 50 %",
    "no",
    "A",
    "BWL und zwei Jahre HR-Erfahrung werden akzeptiert. Fachlich sehr passend, wirtschaftlich wegen des Umfangs nicht tragfähig.",
  ],
  [
    47,
    "Projektmanager Handwerk und Digitalisierung",
    "Regh",
    "Duisburg",
    null,
    "Aktuell offen · Vollzeit",
    "Etwa 42.000–50.000 Euro",
    "borderline",
    "A−/B+",
    "Digitales Onboarding, Personalakten, administrative Prozesse, ERP und Anbieter. Sehr praxisnah, aber beim Gehalt die obere Grenze aktiv verhandeln.",
  ],
  [
    48,
    "Projektmanager AI und Automation",
    "Schmitt Engineering",
    "Mülheim",
    null,
    "Aktuell offen · Vollzeit · Arbeitnehmerüberlassung",
    "Nicht veröffentlicht",
    "open",
    "B−",
    "AI-Use-Cases, Business Cases, KPIs, Roll-outs, Power Platform/RPA, SQL und Python. Formell werden technische beziehungsweise Data-Science-Abschlüsse bevorzugt.",
  ],
  [
    49,
    "Projektmanager PMO für Strategie- und Prozessprojekte",
    "Deuka",
    "Düsseldorf",
    null,
    "Aktuell laut Stellenportal · Vollzeit",
    "Nicht veröffentlicht",
    "open",
    "A−/B+",
    "Strategie, Prozesse, Asana, KPIs, Risiken, Meilensteine und Workshops. Nur über Drittquelle verifiziert; Arbeitgeberportal vor Bewerbung gegenprüfen.",
  ],
  [
    50,
    "Mitarbeit Projekt „Master öffentliche Verwaltung“",
    "HSPV NRW",
    "Gelsenkirchen",
    "2026-08-24",
    "50 % · befristet bis 30.06.2030",
    "EG 11 TV-L bei 50 %",
    "no",
    "A−",
    "BWL wird akzeptiert. Service Learning, AI-gestütztes Blended Learning, Koordination und digitale Materialien passen sehr gut; der Umfang ist wirtschaftlich nicht ausreichend.",
  ],
  [
    51,
    "Mitarbeit AI-gestützte Selbstlernwerkzeuge und digitale Prüfungen",
    "HSPV NRW",
    "Gelsenkirchen",
    "2026-08-10",
    "50 % · befristet bis 2030",
    "EG 13 TV-L bei 50 %",
    "no",
    "B−/C",
    "Python und AI-Lernwerkzeuge passen; gefordert wird jedoch ein einschlägiger Masterabschluss.",
  ],
  [
    52,
    "BCB Officer / Business Continuity",
    "Stadtsparkasse Wuppertal",
    "Wuppertal",
    "2026-08-07",
    "Unbefristet · 50 %",
    "TVöD bei 50 %",
    "no",
    "B−/C",
    "BWL wird akzeptiert; BIA, RIA, Notfallhandbuch und Übungen. Erforderlich sind Sparkassen- oder Bankerfahrung und BCM-Weiterbildung.",
  ],
  [
    53,
    "Sachbearbeitung Fortbildungen und Lehrgänge",
    "Akademie für Öffentliches Gesundheitswesen",
    "Düsseldorf",
    "2026-08-07",
    "Vorgesehener Beginn 01.09.2026",
    "EG 8 TV-L",
    "no",
    "A−/B",
    "Teilnehmenden- und Dozentenbetreuung, digitale Medien und Veranstaltungsorganisation. Gefordert wird eher eine kaufmännische Ausbildung; das Studium ist höherwertig.",
  ],
  [
    54,
    "Projektunterstützung Digitalisierung",
    "Stadt Ratingen",
    "Ratingen",
    "2026-08-17",
    "Unbefristet",
    "EG 8 / A 8",
    "no",
    "A−/B",
    "Projektpläne, Ressourcen, Serviceportal und OZG. Inhaltlich guter Einstieg, aber für die wirtschaftlichen Verpflichtungen zu niedrig eingruppiert.",
  ],
  [
    55,
    "Sachbearbeitung Kommunales Krisenmanagement / BCM – anspruchsvollere Variante",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-10",
    "Unbefristet",
    "EG 11 / A 12",
    "yes",
    "B−/C",
    "Im Gegensatz zur EG-10-Stelle werden Kenntnisse in ISO 22301, BSI 200-4 und ISO 22361 ausdrücklich vorausgesetzt.",
  ],
  [
    56,
    "BCM-Architekt",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-10",
    "Unbefristet",
    "EG 11 / A 11",
    "yes",
    "B−/C",
    "Formell Informatik, Wirtschaftsinformatik, Risiko- oder Sicherheitsmanagement oder vergleichbarer Abschluss; zusätzlich BSI 200-4, BIA und IT-Infrastruktur.",
  ],
  [
    57,
    "Informationssicherheitsbeauftragter",
    "HSPV NRW",
    "Gelsenkirchen",
    "2026-08-18",
    "Unbefristet · Kurzinfo mit Frist 18.08.2026",
    "EG 12",
    "yes",
    "C",
    "ISMS, Risiken, Incidents und Krisen passen thematisch; gefordert werden jedoch mehrjährige Informationssicherheit sowie BSI- und ISO-27001-Praxis. Der Detailtext enthält offenbar einen Jahreszahlfehler.",
  ],
  [
    58,
    "Referent Notfall- und Krisenmanagement",
    "Akademie für Öffentliches Gesundheitswesen",
    "Düsseldorf",
    "2026-08-16",
    "Arbeitsumfang nicht näher veröffentlicht",
    "EG 12 TV-L",
    "yes",
    "B−/C",
    "Krisenstäbe, Workshops und Bevölkerungsschutz; einschlägiges Studium in Sicherheits-, Gesundheits- oder Krisenmanagement wird erwartet.",
  ],
  [
    59,
    "Referent Digitale Verwaltung",
    "Justizministerium NRW",
    "Düsseldorf",
    "2026-07-31",
    "Zugang höherer Dienst beziehungsweise entsprechende Laufbahnvoraussetzungen",
    "Nicht näher veröffentlicht",
    "open",
    "C",
    "Digitale Justizvollzugsverwaltung, E-Akte, my.NRW und Datenschutz passen inhaltlich; der Zugang ist auf den höheren Dienst beziehungsweise entsprechende Master- oder Laufbahnvoraussetzungen ausgerichtet.",
  ],
  [
    60,
    "Leitung einer Organisationseinheit",
    "Stadt Neuss",
    "Neuss",
    "2026-08-08",
    "Unbefristet",
    "EG 12 / A 13",
    "yes",
    "B−/C",
    "BWL mit Organisationsschwerpunkt wird akzeptiert; verlangt wird jedoch mehrjährige Organisationsberatung innerhalb einer Behörde und Führung eines Teams.",
  ],
  [
    61,
    "Beratung Sozial- und Integrationsmanagement für Geflüchtete",
    "Stadt Haan",
    "Haan",
    "2026-08-09",
    "Arbeitsumfang nicht näher veröffentlicht",
    "Nicht näher veröffentlicht",
    "open",
    "C",
    "Kommunikations- und Vermittlungsfähigkeit passen, aber üblicherweise wird ein Studium der Sozialarbeit/Sozialpädagogik oder eine anerkannte vergleichbare Qualifikation verlangt.",
  ],
  [
    62,
    "Steuerungsunterstützung der technischen Betriebsleitung",
    "Stadt Düsseldorf",
    "Düsseldorf",
    "2026-08-06",
    "Unbefristet",
    "EG 11",
    "yes",
    "C",
    "Projektkoordination, Strategie, Controlling und Gremien passen; ein technischer beziehungsweise ingenieurwissenschaftlicher Abschluss wird vorausgesetzt.",
  ],
  [
    63,
    "Abteilungsleitung Versorgungsinnovationen / Head of Healthcare Innovation",
    "KV Nordrhein",
    "Düsseldorf",
    "2026-07-31",
    "Arbeitsumfang nicht näher veröffentlicht",
    "Nicht näher veröffentlicht",
    "open",
    "B−/C",
    "Digital-Health-Strategie und Innovationsprojekte sind attraktiv; verlangt werden Führungserfahrung, Gesundheitsmarktkenntnisse und aktuelle große Projekterfolge.",
  ],
  [
    64,
    "Sachbearbeitung studiengangsbezogene Evaluation",
    "HSPV NRW",
    "Gelsenkirchen",
    "2026-08-20",
    "Befristet bis 30.06.2030",
    "EG 13",
    "yes",
    "C",
    "Qualitätsmanagement, Prozessportal und Evaluation; ein sozialwissenschaftlicher Master mit empirischer Forschung wird verlangt.",
  ],
  [
    65,
    "Spezialist Künstliche Intelligenz",
    "Bank11",
    "Neuss",
    null,
    "Aktuell offen · Vollzeit",
    "Privatwirtschaftlich",
    "open",
    "B−/C",
    "Entwicklung kognitiver Systeme und LLM-Lösungen passt; gefordert werden ein Informatikabschluss oder Vergleichbares und etwa drei Jahre professionelle AI- oder Robotik-Entwicklung.",
  ],
  [
    66,
    "Referent Datenschutz",
    "Bank11",
    "Neuss",
    null,
    "Aktuell offen · Vollzeit",
    "Privatwirtschaftlich",
    "open",
    "C",
    "Datenschutzberatung und Governance sind interessant; die Stelle verlangt jedoch ein juristisches Studium und entsprechende Berufspraxis.",
  ],
  [
    67,
    "IT-Projektleitung Finanzbereich / S4HANA",
    "Stadt Köln",
    "Köln",
    "2026-08-18",
    "Unbefristet · Voll- oder Teilzeit",
    "EG 13 TVöD-IKT",
    "yes",
    "C",
    "Projekt- und BWL-Anteile passen, aber ein einschlägiger IT-Abschluss und substanzielle SAP-S/4HANA-Erfahrung sind erforderlich.",
  ],
  [
    68,
    "Projektmanager Laborneubau",
    "CVUA-RRW",
    "Krefeld",
    "2026-08-02",
    "Unbefristet",
    "EG 13 TVöD",
    "yes",
    "C",
    "Bauherrenvertretung, Kosten, Termine, Verträge und externe Planer; zwingend ist ein Bau- oder Architekturabschluss mit großer Bauprojekterfahrung.",
  ],
  [
    69,
    "Projektmanager kaufmännische Projektsteuerung",
    "BLB NRW",
    "Düsseldorf",
    "2026-07-29",
    "Unbefristet · bis 60 % mobil",
    "Etwa 51.460–82.590 Euro",
    "yes",
    "C",
    "Im Rechercheanhang als thematisch ähnliche Stelle mit erheblicher formaler Hürde geführt.",
  ],
  [
    70,
    "Initiativbewerbung für IT-Projekte und digitale Finanzverwaltung",
    "Rechenzentrum der Finanzverwaltung NRW",
    "Kaarst oder Paderborn",
    "2027-01-31",
    "Initiativbewerbung",
    "Abhängig vom Einsatz",
    "open",
    "C",
    "Im Rechercheanhang als langfristige Initiativoption für IT-Projekte und digitale Finanzverwaltung geführt.",
  ],
  [
    71,
    "Sachbearbeitung Inbetriebnahmemanagement",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-20",
    "Unbefristet",
    "EG 11",
    "yes",
    "C",
    "Projekt-, Prozess- und Koordinationsanteile passen; verlangt werden Ingenieurstudium, technische Gebäudeausrüstung und Facility-Management-Erfahrung.",
  ],
  [
    72,
    "Sachbearbeitung Energiemanagement",
    "Stadt Wuppertal",
    "Wuppertal",
    "2026-08-16",
    "Unbefristet",
    "EG 10",
    "yes",
    "C",
    "Zukunftsfestes Projekt- und Nachhaltigkeitsfeld, aber fachtechnische Energie- oder Ingenieurqualifikation ist voraussichtlich zwingend.",
  ],
] as const satisfies readonly VacancySeed[];

function tierFor(rank: number): ApplicationResearchTier {
  if (rank <= 32) return "top";
  if (rank <= 54) return "plausible";
  return "stretch";
}

function vacancy(seed: VacancySeed): ApplicationProcess {
  const [
    rank,
    jobTitle,
    company,
    location,
    deadline,
    publishedTerms,
    compensation,
    salaryOutlook,
    fitRating,
    researchSummary,
  ] = seed;
  return {
    id: `vacancy-${rank}`,
    researchRank: rank,
    researchTier: tierFor(rank),
    shortlisted: SHORTLIST.has(rank),
    jobTitle,
    company,
    location,
    deadline,
    publishedTerms,
    compensation,
    salaryOutlook,
    fitRating,
    researchSummary,
    sourceUrl: "",
    sourceVerifiedAt: VERIFIED_AT,
    status: "research",
    appliedAt: null,
    applicationChannel: "",
    appliedTerms: "",
    contactPerson: "",
    contactEmail: "",
    nextStep: deadline
      ? "Bewerbungsentscheidung treffen"
      : "Ausschreibungsstatus prüfen und priorisieren",
    nextStepAt: deadline,
    notes: "",
    artifacts: [],
  };
}

export const APPLICATION_RESEARCH: ApplicationProcess[] =
  VACANCY_SEEDS.map(vacancy);

export function mergeApplicationResearch(
  existing: ApplicationProcess[] | undefined,
): ApplicationProcess[] {
  const saved = Array.isArray(existing) ? existing : [];
  const savedById = new Map(saved.map((application) => [application.id, application]));
  const seeded = APPLICATION_RESEARCH.map((application) => {
    const current = savedById.get(application.id);
    if (!current) return { ...application, artifacts: [] };
    return {
      ...application,
      ...current,
      shortlisted:
        typeof current.shortlisted === "boolean"
          ? current.shortlisted
          : application.shortlisted,
      artifacts: Array.isArray(current.artifacts) ? current.artifacts : [],
    };
  });
  const own = saved.filter(
    (application) =>
      !application.id.startsWith("vacancy-") ||
      !APPLICATION_RESEARCH.some((seed) => seed.id === application.id),
  );
  return [...seeded, ...own];
}

export function createEmptyApplication(id: string): ApplicationProcess {
  return {
    id,
    researchRank: null,
    researchTier: "own",
    shortlisted: false,
    jobTitle: "Neue Bewerbung",
    company: "",
    location: "",
    deadline: null,
    publishedTerms: "",
    compensation: "",
    salaryOutlook: "open",
    fitRating: "",
    researchSummary: "",
    sourceUrl: "",
    sourceVerifiedAt: new Date().toISOString().slice(0, 10),
    status: "draft",
    appliedAt: null,
    applicationChannel: "",
    appliedTerms: "",
    contactPerson: "",
    contactEmail: "",
    nextStep: "Stellenanzeige und Bewerbungsunterlagen vervollständigen",
    nextStepAt: null,
    notes: "",
    artifacts: [],
  };
}
