import type { AppState, IntegrationConfig } from "./types";

const dayAt = (offset: number, hour = 9, minute = 0): string => {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  date.setDate(date.getDate() + offset);
  return date.toISOString();
};

const dateOnly = (offset: number): string => dayAt(offset).slice(0, 10);

export const DEFAULT_INTEGRATIONS: IntegrationConfig = {
  calendarId: "gerrit.fabisch2024@gmail.com",
  calendarEmbedUrl:
    "https://calendar.google.com/calendar/embed?src=gerrit.fabisch2024%40gmail.com&ctz=Europe%2FBerlin",
  driveFolderUrl:
    "https://drive.google.com/drive/folders/1_XCyuIovFJQSQ80zVy3gVkBuM8Tutgwe",
  driveLocalPath: "G:\\Meine Ablage\\Unterlagen und Dokumente",
  gmailAccount: "gerrit.fabisch2024@gmail.com",
};

export function createDemoState(ownerName = "Gerri"): AppState {
  return {
    schemaVersion: 1,
    revision: 1,
    updatedAt: new Date().toISOString(),
    ownerName,
    monthlyBudget: 1700,
    points: 1240,
    rhythmDays: 5,
    tasks: [
      {
        id: "task-focus",
        title: "Versicherungsunterlagen prüfen",
        area: "finanzen",
        quadrant: "do",
        dueAt: dayAt(0, 17),
        estimateMinutes: 20,
        progress: 35,
        completed: false,
        confidential: true,
      },
      {
        id: "task-calendar",
        title: "Zahlungstermine für den Monat planen",
        area: "finanzen",
        quadrant: "plan",
        dueAt: dayAt(1, 12),
        estimateMinutes: 15,
        progress: 0,
        completed: false,
        confidential: true,
      },
      {
        id: "task-documents",
        title: "Wichtige Unterlagen in Drive ordnen",
        area: "persoenlich",
        quadrant: "plan",
        dueAt: dayAt(3, 18),
        estimateMinutes: 30,
        progress: 60,
        completed: false,
        confidential: true,
      },
      {
        id: "task-walk",
        title: "20 Minuten an die frische Luft",
        area: "gesundheit",
        quadrant: "do",
        dueAt: dayAt(0, 16),
        estimateMinutes: 20,
        progress: 0,
        completed: false,
        confidential: false,
      },
    ],
    costs: [
      {
        id: "cost-groceries",
        title: "Wocheneinkauf",
        category: "Lebensmittel & Haushalt",
        amount: 68.4,
        dueAt: dayAt(-2, 10),
        cadence: "once",
        status: "paid",
        payee: "Supermarkt",
        contactEmail: "",
        note: "Beispieldatensatz",
        confidential: true,
      },
      {
        id: "cost-internet",
        title: "Internet",
        category: "Wohnen",
        amount: 44.99,
        dueAt: dayAt(3, 9),
        cadence: "monthly",
        status: "due",
        payee: "Anbieter",
        contactEmail: "",
        note: "Monatlicher Fixkosten-Beispielposten",
        confidential: true,
      },
      {
        id: "cost-energy",
        title: "Stromabschlag",
        category: "Wohnen",
        amount: 72,
        dueAt: dayAt(7, 9),
        cadence: "monthly",
        status: "planned",
        payee: "Versorger",
        contactEmail: "",
        note: "Monatlicher Fixkosten-Beispielposten",
        confidential: true,
      },
      {
        id: "cost-insurance",
        title: "Haftpflichtversicherung",
        category: "Versicherungen",
        amount: 89,
        dueAt: dayAt(12, 9),
        cadence: "yearly",
        status: "planned",
        payee: "Versicherung",
        contactEmail: "",
        note: "Jährlicher Beispielposten",
        confidential: true,
      },
      {
        id: "cost-transport",
        title: "Mobilität",
        category: "Mobilität",
        amount: 58,
        dueAt: dayAt(-7, 8),
        cadence: "monthly",
        status: "paid",
        payee: "Mobilitätsanbieter",
        contactEmail: "",
        note: "Beispieldatensatz",
        confidential: true,
      },
    ],
    incomes: [],
    accountBalances: {
      paypal: null,
      revolut: null,
      updatedAt: null,
    },
    documents: [
      {
        id: "doc-root",
        name: "Persönlicher Drive-Ordner",
        folderPath: "Persönlich",
        kind: "folder",
        driveUrl: DEFAULT_INTEGRATIONS.driveFolderUrl,
        fileId: null,
        modifiedAt: dayAt(-1),
        tags: ["Google Drive", "Startpunkt"],
        confidential: true,
      },
      {
        id: "doc-insurance",
        name: "Versicherungsunterlagen",
        folderPath: "Persönlich/Finanzen & Verträge/Versicherungen",
        kind: "pdf",
        driveUrl: DEFAULT_INTEGRATIONS.driveFolderUrl,
        fileId: null,
        modifiedAt: dayAt(-4),
        tags: ["Beispiel", "Prüfen"],
        confidential: true,
      },
      {
        id: "doc-rent",
        name: "Mietunterlagen",
        folderPath: "Persönlich/Wohnen/Miete",
        kind: "document",
        driveUrl: DEFAULT_INTEGRATIONS.driveFolderUrl,
        fileId: null,
        modifiedAt: dayAt(-9),
        tags: ["Beispiel", "Wohnen"],
        confidential: true,
      },
      {
        id: "doc-tax",
        name: "Steuerübersicht",
        folderPath: "Persönlich/Finanzen & Verträge/Steuern",
        kind: "sheet",
        driveUrl: DEFAULT_INTEGRATIONS.driveFolderUrl,
        fileId: null,
        modifiedAt: dayAt(-12),
        tags: ["Beispiel", "Finanzen"],
        confidential: true,
      },
    ],
    calendarEvents: [
      {
        id: "event-focus",
        title: "Fokusblock: Unterlagen sortieren",
        startAt: dayAt(0, 15, 30),
        endAt: dayAt(0, 16, 15),
        source: "kompass",
        kind: "focus",
        private: true,
      },
      {
        id: "event-week",
        title: "Wochenplanung",
        startAt: dayAt(2, 10),
        endAt: dayAt(2, 10, 30),
        source: "kompass",
        kind: "appointment",
        private: true,
      },
    ],
    journal: [
      {
        id: "journal-1",
        date: dateOnly(-1),
        mood: 4,
        text: "Die wichtigsten Dinge waren klarer als gedacht.",
        win: "Einen offenen Punkt abgeschlossen.",
        nextStep: "Morgen mit einer kleinen Aufgabe starten.",
      },
    ],
  };
}
