"""Central constants for Streamlit session state keys and defaults."""

SS_TODOS: str = "todos"
SS_STATS: str = "stats"
SS_SETTINGS: str = "settings"
SS_GAMIFICATION: str = "gamification"

AI_ENABLED_KEY: str = "ai_enabled"
AI_QUADRANT_RATIONALE_KEY: str = "ai_quadrant_rationale"
AI_GOAL_SUGGESTION_KEY: str = "ai_goal_suggestion"
AI_MOTIVATION_KEY: str = "ai_motivation_message"
GOAL_SUGGESTED_VALUE_KEY: str = "suggested_goal_daily"
SETTINGS_GOAL_DAILY_KEY: str = "settings_goal_daily"
NEW_TODO_TITLE_KEY: str = "new_todo_title"
NEW_TODO_DUE_KEY: str = "new_todo_due"
NEW_TODO_QUADRANT_KEY: str = "new_todo_quadrant"
NEW_TODO_QUADRANT_PREFILL_KEY: str = "new_todo_quadrant_prefill"
NEW_TODO_RESET_TRIGGER_KEY: str = "new_todo_reset_trigger"
NEW_TODO_CATEGORY_KEY: str = "new_todo_category"
NEW_TODO_PRIORITY_KEY: str = "new_todo_priority"
NEW_TODO_DESCRIPTION_KEY: str = "new_todo_description"
AVATAR_PROMPT_INDEX_KEY: str = "avatar_prompt_index"
FILTER_SHOW_DONE_KEY: str = "filter_show_done"
FILTER_SELECTED_CATEGORIES_KEY: str = "filter_selected_categories"
FILTER_SORT_OVERRIDE_KEY: str = "filter_sort_override"
